### ISSUE TITLE
Black screen while PowerToy's FancyZones are active

### ISSUE THREAD

**Issue by koppor** [NickeManarin/ScreenToGif#762]
When the [FancyZones module of PowerToys](https://github.com/microsoft/PowerToys/wiki/FancyZones-Overview) is active and I move the recording window to another monitor, ScreenToGif background gets black and ScreenToGif is unresponsible:

![image](https://user-images.githubusercontent.com/1366654/100654522-3bdf0480-334a-11eb-83e6-b782ff1b6d58.png)

```yaml
ScreenToGif: 2.27.3
PowerToys: 0.25.0
Windows build number: 17763.1577
```

Refs https://github.com/microsoft/PowerToys/issues/143
